
package Interfaz;

import Entidades.vcliente;
import Entidades.vhabitacion;
import Atributos.Conexion;
import Atributos.LoCliente;
import Atributos.LoHabi;
import java.awt.HeadlessException;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Habitaciones extends javax.swing.JDialog {

    private Conexion mysql = new Conexion();
    private LoHabi mysql1 = new LoHabi();
    private Connection cn = mysql.conectar(); 
    private String sSQL = "";
    private String sSQL2 = "";
    public Integer totalregistros;
 
    public Habitaciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
          setLocationRelativeTo(null);
          
          
           mostrar("");
           
         //cambia la imagen de la tacita de cafe
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Reservacion.png")).getImage());
           
          jButton_Atras.setIcon(setIcono("/Imagenes/Atras.png", jButton_Atras));
        //A la hora de precionar haga un enfoque de click
        jButton_Atras.setPressedIcon(setIconoPresionado("/Imagenes/Atras.png",jButton_Atras,2,2));
        
        jButton_Guardar.setIcon(setIcono("/Imagenes/Guardar.png", jButton_Guardar));
        //A la hora de precionar haga un enfoque de click
        jButton_Guardar.setPressedIcon(setIconoPresionado("/Imagenes/Guardar.png",jButton_Guardar,2,2));
        
        jButton_Cancelar.setIcon(setIcono("/Imagenes/Cancelar.png", jButton_Cancelar));
        //A la hora de precionar haga un enfoque de click
        jButton_Cancelar.setPressedIcon(setIconoPresionado("/Imagenes/Cancelar.png",jButton_Cancelar,2,2));
        
        jButton_eliminar.setIcon(setIcono("/Imagenes/Borrar.png", jButton_eliminar));
        //A la hora de precionar haga un enfoque de click
        jButton_eliminar.setPressedIcon(setIconoPresionado("/Imagenes/Borrar.png",jButton_eliminar,2,2));
        
           jButton_editar.setIcon(setIcono("/Imagenes/Updatee.png", jButton_editar));
        //A la hora de precionar haga un enfoque de click
        jButton_editar.setPressedIcon(setIconoPresionado("/Imagenes/Updatee.png",jButton_editar,2,2));
       
        
    }
  /**
  * 
  * @param buscar Busca dentro de la clase LoCliente y lo muestra en pantalla lo que esta
  * almacenado en la base de datos
  * 
  **/   
    void mostrar(String buscar) {
        try {
            DefaultTableModel modelo;
            LoHabi habi = new LoHabi();
            modelo = habi.mostrar(buscar);

            jTable_Habitaciones.setModel(modelo);
        
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }
    private String accion = "guardar";
       
    /**
    *  Limpia todos los campos de las casillas
    **/
       void limpiarCampos(){
      jTextField_NumHabi.setText("");
       jTextField_Capacidad.setText("");
       jTextField_Tarifa.setText("");
       jComboBox_Disponible.setSelectedItem("");
      
               
           
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Habitaciones = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton_Cancelar = new javax.swing.JButton();
        jButton_Atras = new javax.swing.JButton();
        jButton_Guardar = new javax.swing.JButton();
        jButton_eliminar = new javax.swing.JButton();
        jButton_editar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_NumHabi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Tarifa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_Capacidad = new javax.swing.JTextField();
        jComboBox_Disponible = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hotel Java");

        jPanel2.setBackground(new java.awt.Color(36, 54, 67));

        jTable_Habitaciones.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTable_Habitaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Habitaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_HabitacionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Habitaciones);

        jPanel1.setBackground(new java.awt.Color(36, 54, 67));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton_Cancelar.setBackground(new java.awt.Color(36, 54, 67));
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });

        jButton_Atras.setBackground(new java.awt.Color(36, 54, 67));
        jButton_Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras.png"))); // NOI18N
        jButton_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AtrasActionPerformed(evt);
            }
        });

        jButton_Guardar.setBackground(new java.awt.Color(36, 54, 67));
        jButton_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardarActionPerformed(evt);
            }
        });

        jButton_eliminar.setBackground(new java.awt.Color(36, 54, 67));
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });

        jButton_editar.setBackground(new java.awt.Color(36, 54, 67));
        jButton_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton_Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(36, 54, 67));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Numero Habitacion");

        jTextField_NumHabi.setBackground(new java.awt.Color(82, 79, 79));
        jTextField_NumHabi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField_NumHabi.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_NumHabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NumHabiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tarifa");

        jTextField_Tarifa.setBackground(new java.awt.Color(82, 79, 79));
        jTextField_Tarifa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField_Tarifa.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Tarifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TarifaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Capacidad (Personas)");

        jTextField_Capacidad.setBackground(new java.awt.Color(82, 79, 79));
        jTextField_Capacidad.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField_Capacidad.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Capacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CapacidadActionPerformed(evt);
            }
        });

        jComboBox_Disponible.setBackground(new java.awt.Color(82, 79, 79));
        jComboBox_Disponible.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jComboBox_Disponible.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox_Disponible.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DISPONIBLE", "NO DISPONIBLE" }));
        jComboBox_Disponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_DisponibleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_NumHabi, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jTextField_Tarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox_Disponible, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_NumHabi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Tarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Disponible, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_NumHabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NumHabiActionPerformed

        jTextField_NumHabi.transferFocus();

    }//GEN-LAST:event_jTextField_NumHabiActionPerformed

    private void jTextField_TarifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TarifaActionPerformed

        jTextField_Tarifa.transferFocus();

    }//GEN-LAST:event_jTextField_TarifaActionPerformed

    private void jTextField_CapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CapacidadActionPerformed

        jTextField_Capacidad.transferFocus();

    }//GEN-LAST:event_jTextField_CapacidadActionPerformed

    private void jButton_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AtrasActionPerformed
         /**
          * Sale del JDialog hacia la pantalla principal JFrame
          */
        this.setVisible(false);

       /**
        *  Desconecta la base de datos
        */
       mysql.DesconectarBase();
    }//GEN-LAST:event_jButton_AtrasActionPerformed

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed

        /**
         * Cancelar y limpia los campos JText
         */
        limpiarCampos();
        
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    private void jTable_HabitacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_HabitacionesMouseClicked
 //Hace click en un filas de la tablas y las selecciona en las casillas correspondiente
      int fila = jTable_Habitaciones.rowAtPoint(evt.getPoint());

        jTextField_NumHabi.setText(jTable_Habitaciones.getValueAt(fila, 0).toString());
        jTextField_Capacidad.setText(jTable_Habitaciones.getValueAt(fila, 1).toString());
        jTextField_Tarifa.setText(jTable_Habitaciones.getValueAt(fila, 2).toString());
        jComboBox_Disponible.setSelectedItem(jTable_Habitaciones.getValueAt(fila, 3).toString());
       
    }//GEN-LAST:event_jTable_HabitacionesMouseClicked

    private void jButton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarActionPerformed
        
       /**
         * Muestra una advertencia de que hace faltan campos por completar y lo redirige al campo por rellenar
         * o mas espeficio implementar un método que revice si todos los campos de información
         * estan completos
         **/
        
         if (jTextField_NumHabi.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar el numero de la habitacion");
            jTextField_NumHabi.requestFocus();
            return;
        }
        if (jTextField_Capacidad.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar la capacidad maxima de la habitacion");
            jTextField_Capacidad.requestFocus();
            return;
        }
        
        if (jTextField_Tarifa.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar la tarifa de la habitacon");
            jTextField_Tarifa.requestFocus();
            return;
        }

        vhabitacion dts = new vhabitacion(); 
        LoHabi func = new LoHabi();

        /**
         * Cuando el usuario de la click al boton de guardar esta hace que 
         * Guarde en la base de datos todo lo que el usuario quiera almacenar 
         */
        dts.setNumero_habitacion(jTextField_NumHabi.getText());
        dts.setNumero_personas(jTextField_Capacidad.getText());
        dts.setTarifa_estadia(jTextField_Tarifa.getText());     
        int seleccionado = jComboBox_Disponible.getSelectedIndex();
        dts.setDisponible((String) jComboBox_Disponible.getItemAt(seleccionado));
        
        
       
        //Guardar
        if (accion.equals("guardar")) { 
            if (func.insertar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "el cliente fue registrado satisfactoriamente");
                mostrar("");
            }

        }

        limpiarCampos();
        mostrar("");
        
    }//GEN-LAST:event_jButton_GuardarActionPerformed

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed

        /**
         * Elimina registros de la base de datos
         **/

        if (!jTextField_NumHabi.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "¿Estás seguro de Eliminar el registro de la habitacion?","Confirmar",2);

            if (confirmacion==0) {
                 LoHabi co = new LoHabi();
                vhabitacion dts= new vhabitacion();

                dts.setNumero_habitacion(String.valueOf(jTextField_NumHabi.getText()));
                co.eliminar(dts);
                mostrar("");
                limpiarCampos();
      
            }

          }
    }//GEN-LAST:event_jButton_eliminarActionPerformed

    private void jButton_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editarActionPerformed

        /**
            * Editar los campos de las tablas
            **/
        try{
            String numero_habitacion = jTextField_NumHabi.getText();
            String numero_personas = jTextField_Capacidad.getText();
            String tarifa_estadia = jTextField_Tarifa.getText();
            String disponible = (String) jComboBox_Disponible.getSelectedItem();
            
            /**
             * Instruccion String SQL que me permite editar la tablas habitacion
             **/
            
            String sql ="Update habitacion set numero_habitacion ='"+numero_habitacion+"',"
                    + "numero_personas ='"+numero_personas+"',tarifa_estadia='"+tarifa_estadia+"',disponible='"+disponible+"' WHERE numero_habitacion='"+numero_habitacion+"'";

             /**
             * Ejecuto la instruccion para 
             **/
            PreparedStatement pst=cn.prepareStatement(sql);
            pst.execute();
            mostrar("");
            JOptionPane.showMessageDialog(null, "Se ha modificado con exito");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "ERROR");
            
        }

    }//GEN-LAST:event_jButton_editarActionPerformed

    private void jComboBox_DisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_DisponibleActionPerformed
    }//GEN-LAST:event_jComboBox_DisponibleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Habitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Habitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Habitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Habitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Habitaciones dialog = new Habitaciones(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
        
    }
        public Icon setIcono(String url,JButton boton ){//adapta el icono a la altura o ancho que uno quiera
     ImageIcon icon = new ImageIcon(getClass().getResource(url));
     
     int ancho = boton.getWidth();
     
     int alto = boton.getHeight();
     
     ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho,alto,Image.SCALE_DEFAULT));
     
     return icono;
    }
    //Hace como un click hacia abajo a la hora de tocar la casilla
    public Icon setIconoPresionado(String url, JButton boton, int ancho, int altura){
    
    ImageIcon icon = new ImageIcon(getClass().getResource(url));
    int width = boton.getWidth() - ancho;
    int height = boton.getHeight() - altura;
    
    ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(width, height,Image.SCALE_DEFAULT));
     return icono;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Atras;
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JButton jButton_Guardar;
    private javax.swing.JButton jButton_editar;
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JComboBox<String> jComboBox_Disponible;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Habitaciones;
    private javax.swing.JTextField jTextField_Capacidad;
    private javax.swing.JTextField jTextField_NumHabi;
    private javax.swing.JTextField jTextField_Tarifa;
    // End of variables declaration//GEN-END:variables
}
